plugin: amazon.aws.aws_ec2
regions:
  - eu-central-1
filters:
  instance-state-name: running
  tag:Name: github-ansible-ec2
hostnames:
  - public_ip_address
compose:
  ansible_host: aws_public_ip_address
hostvars_prefix: aws_
